#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : deprecated-pexpect
Version  : 4.6.0
Release  : 54
URL      : https://files.pythonhosted.org/packages/89/43/07d07654ee3e25235d8cea4164cdee0ec39d1fda8e9203156ebe403ffda4/pexpect-4.6.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/89/43/07d07654ee3e25235d8cea4164cdee0ec39d1fda8e9203156ebe403ffda4/pexpect-4.6.0.tar.gz
Summary  : Pexpect allows easy control of interactive console applications.
Group    : Development/Tools
License  : ISC
Requires: deprecated-pexpect-license = %{version}-%{release}
Requires: deprecated-pexpect-python = %{version}-%{release}
Requires: ptyprocess
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3
BuildRequires : ptyprocess

%description
This directory contains scripts that give examples of using Pexpect.
hive.py
This script creates SSH connections to a list of hosts that
you provide. Then you are given a command line prompt. Each
shell command that you enter is sent to all the hosts. The
response from each host is collected and printed. For example,
you could connect to a dozen different machines and reboot
them all at once.

%package legacypython
Summary: legacypython components for the deprecated-pexpect package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the deprecated-pexpect package.


%package license
Summary: license components for the deprecated-pexpect package.
Group: Default

%description license
license components for the deprecated-pexpect package.


%package python
Summary: python components for the deprecated-pexpect package.
Group: Default

%description python
python components for the deprecated-pexpect package.


%prep
%setup -q -n pexpect-4.6.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554324419
export MAKEFLAGS=%{?_smp_mflags}
python2 setup.py build -b py2

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/deprecated-pexpect
cp LICENSE %{buildroot}/usr/share/package-licenses/deprecated-pexpect/LICENSE
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/deprecated-pexpect/LICENSE

%files python
%defattr(-,root,root,-)
